require 'blocks'

# Weaver class store all the information about a weaver file necessary
# to create the processed latex file
class Weaver
	attr_accessor :file, :blocks, :latex
	
	@blocks = []
	
	def file=(file)
		@file = Pathname.new(file)
		load
	end
	
	def cache_path
		Pathname.new("weaver-cache")
	end
	
	def initialize(file)
		self.file = file
	end
	
	def load
		block_type = {
			"" => Block,
			"=" => LatexBlock,
			"=g" => GraphicBlock,
			"=r" => RBlock
		}
		block_re = /<%(=?[rg]?)\s*(.*?)\s*%>/im
		
		
		@blocks = []

		self.latex = file.read.gsub(block_re) do |match|
			type, contents = $1, $2
			b = block_type[type].new(contents, cache_path)
			@blocks << b
			"#<Block:#{b.object_id}>"
		end
	end
	
	def process(remove_cache = false)
		full_cache_path = file.parent + cache_path
		
		FileUtils.rm full_cache_path + "output.pdf", :force => true
		FileUtils.rm_r full_cache_path if remove_cache
		
		FileUtils.mkdir_p(full_cache_path)
		File.open(full_cache_path + "code.r", "w") { |f| f.write r_code }
		%x{r -q --no-save < weaver-cache/code.r > weaver-cache/r.log 2>&1}
		process_latex
		File.open(full_cache_path + "output.tex", "w") { |f| f.write latex }	
		%x{pdflatex  -interaction=nonstopmode -file-line-error-style    %{full_cache_path + "output.tex"}}	
		
		if File.exists? full_cache_path + "output.pdf"
			FileUtils.cp full_cache_path + "output.pdf", file.parent + "output.pdf"
			`open %{file.parent + "output.pdf"}`
		end
		
	end
	
	def process_latex
		self.latex = latex.gsub(/#<([a-z]+):(.*?)>/i) { |match|
			id = $2.to_i
			ObjectSpace._id2ref(id.to_i).latex_code
		}
	end
	
	def r_cache
		(file.parent + cache_path + "cache.rdata")
	end
	
	def r_code
		r_header + blocks.map{|b| b.r_code}.join() + r_footer
	end
	
	def r_header
		%{
			# R code generated by weaver 
			# from #{file.realpath} on #{Date.today} 
			# ---------------------------------------------------------
			
			weaver.width <- 8
			weaver.height <- 5
			
			setwd("#{file.parent.realpath}")
			if (file.exists("#{r_cache}")) load("#{r_cache}")
			library(xtable)	
		}.gsub(/^\s*/, "")
	end

	def r_footer
		%{
			save(list = ls(all=TRUE), file= "#{r_cache}")
		}.gsub(/^\s*/, "")
	end
end