#! /usr/bin/env ruby

$: << "/Users/hadley/documents/weaver/"
require 'optparse'
require 'pathname'
require 'weaver'

clean = false
opts = OptionParser.new do |opts|
	opts.banner = "Usage: weaver [options] file-name"
	opts.on_tails("-h", "--help",  "This help page") { puts opts.to_s}
end

args = opts.parse(ARGV)
if args.length != 1
	opts.warn "Please specify one file to process"
	puts opts.to_s
	exit
end

file = Pathname.new(args[0])
if file.extname == ""
	file = file.dirname + (file.basename.to_s + ".wvr")
end

if !File.exists?(file)
	opts.warn "File does not exist"
end

w = Weaver.new(file)
w.process(clean)
